include:
  - openspy-web-backend/docker-compose.yaml
  - openspy-core/docker-compose.yaml
  - webservices/docker-compose.yaml
services:
  nginx:
    image: nginx:1-alpine
    restart: on-failure
    depends_on:
      - authservices
      - commerceservice
      - competitionservice
      - storageservice
    ports:
      - 80:80
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
  natneg-helper:
    image: "chcniz/openspy-natneg-helper"
    hostname: "natneg-helper"
    restart: on-failure
    depends_on:
      - rabbit
    environment:
      RABBITMQ_URL: amqp://rabbitmq:rabbitmq@rabbit
      UNSOLICITED_PORT_PROBE_DRIVER: 0.0.0.0:30695
      UNSOLICITED_IP_PROBE_DRIVER: unset
      UNSOLICITED_IPPORT_PROBE_DRIVER: unset
      SKIP_ERTL: 1
  qr-service:
    image: "chcniz/openspy-qr-service"
    hostname: "qr-service"
    restart: on-failure
    depends_on:
      - rabbit
    environment:
      RABBITMQ_URL: amqp://rabbitmq:rabbitmq@rabbit
      REDIS_URL: redis://redis:6379
      GEOIP_DB_PATH: /GeoLite2-City.mmdb
    volumes:
      - ./geoip/GeoLite2-City.mmdb:/GeoLite2-City.mmdb
  gamestats-web:
    image: "chcniz/openspy-gamestats-web"
    hostname: "gamestats-web"
    restart: on-failure
    environment:
      GAMESTATS_MONGODB_URI: mongodb://OpenSpy:OpenSpy123@mongo:27017
      PORT: 4000
  stella-web:
    image: "chcniz/openspy-bf2142-stella-web"
    hostname: "stella-web"
    restart: on-failure
    environment:
      API_KEY: ELGAoKHyFPfsWhmWF5F/8uNz2YcdTrojCZbRfvlFwBKJIhDUdvMwM4bmljSsEBq57riyXRij8FoqmxWR8C2BQIEaGG68uFJKcQmJlLY2ntAFOYUloccRCr/eBW8sJZsTIGaIdVdsDeDOrRJR487tfFGNHW2Ezp+oVrZVsd3C9e0VobSE1fXdSFz3R5MIqH3bLprfcDLJL/U8gtvUBegOQI22Vviha24W0/76SQSo72Z7i6GrpU/OnrsjcHQSwyC6VeCTv5JjCP/BSsaCK0Zxw3OlzQsPAprQug9Pwm5MrH/pkkxhqLKcCxjsU25Zj+ipkKOzsO+rmqaIMsK6ILke6w==
      API_ENDPOINT: http://core-web:8080
      MONGODB_URI: mongodb://OpenSpy:OpenSpy123@mongo:27017
      PORT: 4001